prezly/javascript-sdk

.gitignore
jest.config.js
package.json
src/Api/Api.ts
src/Sdk/Coverage/Coverage.ts
src/Sdk/Coverage/index.ts
src/Sdk/Coverage/types.ts
src/Sdk/Sdk.ts
src/Sdk/index.ts
src/Sdk/routing.ts
src/Sdk/types.ts
src/Sdk/utils.ts
src/index.ts
src/sdk.ts
src/types/Category.ts
src/types/Contact.ts
src/types/ContactDuplicateSuggestion.ts
src/types/ContactRef.ts
src/types/Coverage.ts
src/types/Culture.ts
src/types/EntitiesMap.ts
src/types/Entity.ts
src/types/Pagination.ts
src/types/RoomRef.ts
src/types/Story.ts
src/types/StoryLifecycleStatus.ts
src/types/StoryRef.ts
src/types/UserAccountRef.ts
src/types/UserRef.ts
src/types/index.ts

https://app.clubhouse.io/prezly/story/10308/extract-sdk-functionality
There's a ton of changes because of the copied types. These files are exactly the same as in the backend app. The only change is the `Entity` type, which is generic and accepts optional `id` type, while still defaulting to `number` (to match the original).

Feature - SDK

---

src/Sdk/Coverage/Coverage.ts
src/Sdk/Coverage/types.ts
src/Sdk/Sdk.test.js
src/Sdk/utils.ts
src/types/Coverage.ts

- Fix a bug with `pageSize` not being passed as `limit` request param
- Fix wrong coverage ID type (it is actually `number`, but `string` was declared before)
- Update Coverage interface with the latest changes in Prezly APIs (`url` and `published_at` properties)
- Add support for `headline` property
https://app.clubhouse.io/prezly/story/11641/update-prezly-sdk-package
- Add new `headline` property to Coverage interface
- Add new `headline?` property to Coverage create/update requests
<br>
- Add support for soft-deleted coverage
https://app.clubhouse.io/prezly/story/13255/update-prezly-javascript-sdk
- Add new `is_deleted` property to Coverage interface
- Add new `include_deleted` param to Coverage List API function
- Always use `include_deleted: true` for `external_reference_id` lookups

Feature  - Coverage API updates

---

src/Sdk/Coverage/Coverage.ts
src/Sdk/utils.ts

Drop support for ID or Object parameters
- SDK functions do only accept ids now
- Drop unneeded now `buildUriWithId()` function

Refactor - Drop support for ID or Object parameters

---

src/types/Coverage.ts
src/types/Newsroom.ts

DEV-2437
- Add undocumented Newsroom API properties: `newsroom_logo`  and `square_logo`
- Add undocumented Coverage API properties: `display_name` and `avatar_url` (+apply logical order)

[DEV-2437] Fix - Undocumented API properties

---

tsconfig.json

The TypeScript docs confusingly don't specify that `removeComments` option is only applying to JSDoc comments, and that regular comments are always removed on build regardless of this setting.
Update the value to `false`, so now all JSDoc comments on interfaces should be preserved.

[DEV-2461] Update tsconfig to not remove JSDoc comments

---

README.md
src/Sdk/Stories/Stories.ts
src/Sdk/Stories/types.ts
src/index.ts
src/types/Story.ts
src/types/index.ts

DEV-2646
- Update SDK to support optional fields includes. 
It is now possible to fetch stories list with `ExtendedStory` fields
```js
const { stories } = await api.list({ include: ['content', 'preview_image'] });
```
Thanks @yuriyyakym for dramatic simplification of the proposed solution :trophy:

[DEV-2646] Feature - Stories SDK include sparse fields

---

src/types/common/OEmbedInfo.ts

Required for https://github.com/prezly/slate/pull/23/files

Fix - Add screenshot_url attribute to OEmbedInfo

---

src/Sdk/NewsroomCategories/NewsroomCategories.ts

https://linear.app/prezly/issue/DEV-3248/newsroom-categories-api-cannot-update-particular-category
https://linear.app/prezly/issue/DEV-3249/newsroom-categories-api-cannot-get-particular-category
- adds `NewsroomCategories.get`
- adds `categoryId` argument to `NewsroomCategories.update`

[DEV-3248][DEV-3249] Fix - Newsroom categories SDK

---

src/index.ts
src/types/Story.ts
src/types/UserAccountRef.ts
src/types/UserRef.ts
src/types/index.ts

- Add missing props to `UserRef` interface
- Drop `UserAccountRef` interface
Which was really just a desynchronized copy of `UserRef`. It is the same entity.
- Export `UserRef` interface
Related to #45

Fix - UserRef interface

---

src/types/Contact.ts

They were removed in backend long ago.

Drop `is_license_contact` and `is_locked` from Contact type

---

src/endpoints/NotificationSubscriptions/types.ts

This issue was introduced in #164. The API expects just the string id in the `notification_type` field, not the whole Type object

Fix `NotificationSubscriptions.UpdateRequest` type

---

src/endpoints/CampaignRecipients/Client.ts
src/endpoints/CampaignRecipients/types.ts
src/endpoints/Campaigns/Client.ts
src/endpoints/Campaigns/types.ts
src/endpoints/ContactsExports/Client.ts
src/endpoints/ContactsExports/types.ts
src/endpoints/Coverage/Client.ts
src/endpoints/Coverage/types.ts
src/endpoints/NewsroomCategories/Client.ts
src/endpoints/NewsroomCategories/types.ts
src/endpoints/NewsroomGalleries/Client.ts
src/endpoints/NewsroomGalleries/types.ts
src/endpoints/NewsroomLanguages/Client.ts
src/endpoints/NewsroomLanguages/types.ts
src/endpoints/Newsrooms/Client.ts
src/endpoints/Newsrooms/types.ts
src/endpoints/Stories/Client.ts
src/endpoints/Stories/types.ts
src/types/SortOrder.test.js
src/types/SortOrder.ts
src/types/index.ts

Followup on https://github.com/prezly/prezly/pull/12045
- Introduce `SortOrder` type and utilities
- Declare that APIs now support multi-column sorting

[DEV-9503] Feature - Multi-column sorting

---

src/endpoints/NewsroomHub/Client.ts
src/endpoints/NewsroomHub/types.ts

- Update Hub API methods to allow additional settings on hub members
- Also, it's now allowed to link/unlink specific members, instead of doing the whole list at once

[DEV-9713] Update - Newsroom Hub API

---

src/types/Newsroom.ts

- Introduce a consistent name for Newsroom Google Analytics tracking ID prop
The old `ga_tracking_id` is a deprecated alias now.

[DEV-9717] Fix - Newsroom Google Analytics ID prop consistency

---

src/Client.ts

This will allow to access the API application, bypassing specialized per-endpoint clients code. Particularly useful to access undocumented (yet) APIs.

[DEV-9672] Expose generic API client

---

src/types/Story.ts

[QRF-836] Deprecate Story `lifecycle_status` in favour of `status`

---

src/types/SenderDomain.ts

It's `is_upgrade_required` to indicate that the domain is using a deprecated setup that has to be upgraded.

[DEV-10125] Declare a new prop on Sender Domain API

---

src/types/Contact.ts
src/types/ContactDuplicateSuggestion.ts

- Introduce a Ref projection of `ContactDuplicateSuggestion`, and use it inside `Contact.duplicate_contacts`
- While the full `ContactDuplicateSuggestion` (with full `Contact`) will now be used as a result of Contact Duplicates API

[DEV-10349] Change - Contact Duplicates API full record vs ref

---

package-lock.json
package.json
src/http/lib.ts

Currently the only issue I found that prevented the package from working on the Edge Runtime was usage of Node.js URL. This PR fixes this by adding an extra check for `EdgeRuntime` property on the global object and returning global `URL` property in that case.

[CARE-1524] Add support for Edge Runtime

---

src/types/Category.ts
src/types/Culture.ts

To avoid mistakes of misusing ISO code with dashes as Prezly Culture codes.
E.g. `nl_BE` vs `nl-BE`
This problem shines in the `@prezly/theme-kit-intl` package, where different types of codes are being used in different contexts.
I saw this approach in the Next.js codebase: [alternative-urls-types.ts:418-423](https://github.com/vercel/next.js/blob/99e584c70e6277d06c0aca2a8c822f154988adde/packages/next/src/lib/metadata/types/alternative-urls-types.ts#L418-L423)

Make `Culture[code]` typing stricter

---

src/types/Category.ts
src/types/SortOrder.ts
tsconfig.json

Followup on #260  
With previous approach, TS would always think that `Object.values(category.i18n)` can contain undefined. So doing any map/forEach would require to add unnecessary checks for emptiness.
The original intent behind declaring `i18n` as `Parital<...>` is better to guard against by enabling the `noUncheckedIndexedAccess` TS compiler options.
See https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess

[DEV-11988] Fix Category `i18n` property typing

---

src/types/Category.ts

It's only present in the full `Category` object, which is already declared as needed:
https://github.com/prezly/javascript-sdk/blob/312713e6f2c612d29402fe0abdc2d93ba6991265/src/types/Category.ts#L12-L15

[CARE-4340] `CategoryRef` does not have `stories_number` property

---

src/types/Category.ts

Depends on https://github.com/prezly/prezly/pull/14422
- Split `Category.Translation` and `CategoryRef.Translation` shapes
- Add `public_story_number` to `Category.Translation` API

[CARE-4340] Add `public_stories_number` to `Category.Translation`

---

src/endpoints/NewsroomContacts/Client.ts

The promise was never returned so any consumer code waiting for the API call to finish would happen instantly.

[CARE-4547] Fix - Return promise when hitting the order endpoint

---

src/types/Story.ts

It was a mistake -- the API backend does not provide it for StoryRef.
Introduced by me in #268

[DEV-12202] Drop `custom_slug` property from StoryRef

---

src/types/NewsroomContact.ts

The API returns this property but it is not declared in the type.

Feature - Add site property to NewsroomContact type

---

src/types/common/OEmbedInfo.ts

We're getting `author` from API, not `author_name`

Fix OEmbedInfo author field

---

src/endpoints/Coverage/types.ts
src/types/CoverageEntry.ts

@marko-ogg please implement related property on back-end side. Also let me know if the property should be renamed.
I've noticed that we have both `id` and `uuid` props in integration run entry, so I am unsure if I've chosen the correct one for referencing (uuid).

[CARE-6230] Feature - Store integrationRunUuid in coverage entry

---

src/endpoints/Coverage/types.ts

The data will be used for matching existing or creating new contacts.
Based on https://github.com/prezly/prezly/pull/15744

[DEV-13845] Allow passing objects as coverage contact pointers

---

src/endpoints/Stories/types.ts
src/types/Story.ts

`uploadcare_assets_group_uuid` is returned by default and doesn't need to be an extra field

Fix - Drop `uploadcare_assets_group_uuid` from extra fields

---

src/types/Newsroom.ts

This property was already declared in the [Prezly app](https://github.com/prezly/prezly/blob/2203bafb4167205ebcce4cf8cb944ad671f1da20/apps/backend/resources/javascripts/%40types/%40prezly/sdk/index.d.ts#L7) but now we need it in the Bea theme as well so I'm just adding it here.

Feature - Add active_theme_preset property to Newsroom
