prezly/javascript-sdk

package-lock.json
package.json
src/Sdk/Coverage/Coverage.ts
src/Sdk/Coverage/types.ts
src/types/index.ts

https://app.clubhouse.io/prezly/story/10308/extract-sdk-functionality
#4 showed incorrect diff because this branch is based off #3 and the commits were merged in the incorrect branch. I closed #4 in favor of this PR.  
Changes in this PR are already published as `@prezly/sdk@beta`.

Feature - More SDK Functions

---

README.md
package-lock.json
package.json
setupJest.js
src/Api/Api.test.js
src/Api/Api.ts
src/Api/ApiError.ts
src/Api/createRequest.ts
src/Api/types.ts
tsconfig.json

https://app.clubhouse.io/prezly/story/10498/support-both-node-and-browser

Feature - replace node-fetch with cross-fetch

---

src/Sdk/ApiClient.ts
src/Sdk/Coverage/Coverage.ts
src/Sdk/routing.ts
src/Sdk/utils.ts

Mentioned here: https://github.com/prezly/javascript-sdk/pull/8#discussion_r350152859

Fix - Move buildUrl and buildUrlWithId to SDK utils

---

.github/workflows/nodejs.yml
package.json
src/Sdk/Coverage/index.ts
src/Sdk/index.ts
src/index.ts

It's nice to have access to these interfaces when writing consuming libraries.
Like Alex has it here for Belga syncing code:
https://github.com/prezly/belga-sync/blob/247774b69ba60d7380af62937b3cfbd3a1b6b875/src/util/belga-importer.ts#L5
```ts
import { CoverageCreateRequest } from '@prezly/sdk/dist/Sdk/Coverage/types';
```

Feature - Export all types & request/response interfaces

---

package.json
src/Sdk/Coverage/index.ts
src/Sdk/Coverage/types.ts
src/Sdk/index.ts
src/index.ts

[[branch CH13066]](https://app.clubhouse.io/prezly/story/13066/implement-a-nodejs-cron-job-to-feed-belga-api-results-into-prezly)

Feature - Include oembed as a property of coverage

---

.github/workflows/nodejs.yml
src/Sdk/NewsroomCategories/NewsroomCategories.ts
src/Sdk/NewsroomCategories/index.ts
src/Sdk/NewsroomCategories/types.ts
src/Sdk/Sdk.ts
src/Sdk/index.ts
src/Sdk/routing.ts
src/types/Category.ts

PJS-2
- Implement Newsroom Categories API SDK

Feature - Newsroom Categories API SDK [PJS-2]

---

.gitignore
src/Sdk/NewsroomSubscriptions/NewsroomSubscriptions.ts
src/Sdk/NewsroomSubscriptions/index.ts
src/Sdk/NewsroomSubscriptions/types.ts
src/Sdk/routing.ts

- Support Newsroom Subscriptions API in SDK.

[DEV-1571] Feature - Newsroom Subscriptions SDK

---

package-lock.json
package.json
src/types/Story.ts

- Use `@prezly/slate-types` package to type hint v3 stories `content` prop

Feature - Type-hint Story `content` property

---

src/Sdk/Coverage/Coverage.ts
src/Sdk/NewsroomCategories/NewsroomCategories.ts
src/Sdk/NewsroomContacts/NewsroomContacts.ts
src/Sdk/NewsroomSubscriptions/NewsroomSubscriptions.ts
src/Sdk/Newsrooms/Newsrooms.ts
src/Sdk/Stories/Stories.ts
src/types/Coverage.ts
src/types/Newsroom.ts
src/types/NewsroomContact.ts
src/types/Story.ts

- Promote `uuid` as primary identifiers for:
* Newsroom
* NewsroomContact
* Story
* Coverage

[DEV-2388] Feature - Promote UUID

---

src/types/Story.ts

Fixes DEV-2425
- Fix inaccurate type for `Story.content` property

[DEV-2425] Fix - Story content type

---

src/Sdk/NewsroomLanguages/NewsroomLanguages.ts
src/Sdk/NewsroomLanguages/index.ts
src/Sdk/NewsroomLanguages/types.ts
src/Sdk/Sdk.ts
src/Sdk/index.ts
src/Sdk/routing.ts
src/index.ts
src/types/NewsroomCompanyInformation.ts
src/types/NewsroomLanguageSettings.ts
src/types/index.ts

DEV-2511
- Implement Newsroom Languages API SDK

[DEV-2511] Feature - Newsroom Languages API

---

src/Sdk/NewsroomLanguages/NewsroomLanguages.ts
src/Sdk/NewsroomLanguages/lib.ts
src/Sdk/NewsroomLanguages/types.ts

DEV-2438
- Extend Newsroom Languages API functionality
Related to #30

[DEV-2438] Feature - Newsroom Languages API (part 2)

---

src/Api/lib.ts

Fixes https://github.com/prezly/javascript-sdk/issues/37

Fix - Error with "url" dependency when using SDK in the browser

---

src/types/Newsroom.ts
src/types/UserRef.ts

- Remove the dropped `manual_subscription_management` property from `NewsroomRef` 
- Update `UserRef` type to its latest shape

Fix - Outdated interfaces

---

src/Sdk/Newsrooms/types.ts
src/types/Newsroom.ts

- icon
- timezone
- time_format
- date_format
- is_indexable
- google_analytics_id
- segment_analytics_id

Update Newsroom API interfaces

---

src/types/WebhookEvent.ts

Add supported category events:
- `category.created`
- `category.updated`
- `category.deleted`

Feature - Add supported category events

---

src/types/UnsubscribeReason.ts

- `unwanted`
- `spam`
- `never_signed_up`
- `other`

Add UnsubscribeReason enum values

---

src/Sdk/CampaignRecipients/CampaignRecipients.ts
src/Sdk/CampaignRecipients/index.ts
src/Sdk/CampaignRecipients/types.ts
src/Sdk/Sdk.ts
src/Sdk/index.ts
src/Sdk/routing.ts
src/types/EmailRecipient.ts
src/types/index.ts
src/types/scopes/AllContactsScope.ts
src/types/scopes/CampaignRecipientsScope.ts
src/types/scopes/CampaignReportScope.ts
src/types/scopes/ContactEmployeesScope.ts
src/types/scopes/ContactOrganisationsScope.ts
src/types/scopes/ContactsScope.ts
src/types/scopes/index.ts

- Document `ContactScope` interfaces
- Document `EmailRecipient` interface
- Document Campaign Recipients API

[DEV-3803] Document Campaign Recipients API

---

src/types/Newsroom.ts

Together with:
* https://github.com/prezly/prezly/pull/10874/files

[TF-661] Expose the Segment Write Key in the Newsroom API object

---

package-lock.json
package.json
src/Sdk/Campaigns/Campaigns.ts
src/Sdk/Coverage/Coverage.ts
src/Sdk/DeferredJobsApiClient.ts

With known issues fixed. See https://github.com/prezly/progress-promise/releases/tag/v2.0.0

Upgrade @prezly/progress-promise to v2

---

src/types/Newsroom.ts

Related: https://github.com/prezly/prezly/pull/11266

[MT-5268] Extend `Newsroom` object with `status` property

---

src/types/NewsroomGallery.ts

- name
- description
- thumbnail_image
- creator
- modified_at
- url

Define additional gallery API entity properties

---

.gitignore
src/Sdk/Accounts/Accounts.ts
src/Sdk/Accounts/index.ts
src/Sdk/Accounts/types.ts
src/Sdk/Sdk.ts
src/Sdk/index.ts
src/Sdk/routing.ts
src/types/License.ts
src/types/Permissions.ts
src/types/UserAccount.ts

https://linear.app/prezly/issue/QRF-178/newsroom-preview-link-not-reloaded-when-theme-switched-for-not-live

[QRF-178] Add accounts api

---

src/endpoints/Stories/Client.ts
src/endpoints/Stories/index.ts
src/endpoints/Stories/scopes.ts
src/endpoints/Stories/types.ts
src/types/Story.ts

DEV-9120, DEV-9121, DEV-9122, DEV-9123
Migrate & improve Stories API functions from the application repo

[DEV-9120][DEV-9121][DEV-9122][DEV-9123] Feature - Stories API

---

src/endpoints/NotificationSubscriptions/Client.ts
src/endpoints/NotificationSubscriptions/types.ts
src/types/NotificationSubscription.ts
src/types/NotificationType.ts
src/types/NotificationTypeArea.ts
src/types/index.ts

Followup on #163 
See https://github.com/prezly/javascript-sdk/pull/163#discussion_r1011867456

Avoid using long prefixed names for endpoint payloads

---

src/endpoints/Stories/types.ts

https://github.com/prezly/prezly/pull/11775#discussion_r1017880044

[DEV-9202] Fix inaccurate warning type for Story Change Newsroom API

---

src/http/index.ts
src/index.ts
src/types/Story.ts

- Export `ApiError` class publicly
- Declare Story format version checkers

[DEV-9064] Feature - Various improvements

---

babel.config.cjs.json
package-lock.json
package.json

https://linear.app/prezly/issue/DEV-9540/add-commonjs-config-for-sdk

[DEV-9540] Add commonjs config

---

src/endpoints/Stories/Client.ts

Fixes the root cause of QRF-593

[QRF-593] Fix - SDK generic methods types to disallow extra properties

---

src/Client.ts
src/endpoints/NewsroomHub/Client.ts
src/endpoints/NewsroomHub/index.ts
src/endpoints/NewsroomHub/types.ts
src/endpoints/index.ts
src/routing.ts

[DEV-9676] Add `NewsroomHub` to client

---

src/endpoints/Stories/types.ts
src/types/Story.ts

Related to DEV-9697
- #194 
- #197 
- #200

[QRF-988] Declare missing props in Stories Create/Update API requests

---

src/Client.ts
src/endpoints/PricingTables/Client.ts
src/endpoints/PricingTables/index.ts
src/endpoints/PricingTables/types.ts
src/endpoints/index.ts
src/routing.ts

Related backend changes: https://github.com/prezly/prezly/pull/12622

[DEV-10111] Implement `PricingTables` API SDK

---

src/types/Contact.ts

Should be released after https://github.com/prezly/prezly/pull/13122

[DEV-10465] Add "is_spam_reported" flag to Contacts API

---

src/endpoints/Stories/Client.ts
src/endpoints/Stories/types.ts
src/types/Story.ts

Based on:
- https://github.com/prezly/prezly/pull/13299
- https://github.com/prezly/prezly/pull/13309
- https://github.com/prezly/prezly/pull/13308
- https://github.com/prezly/prezly/pull/13320

[DEV-10922] Add support for v4 Stories format

---

src/types/Story.ts

Based on (and blocked by) https://github.com/prezly/prezly/pull/13652

[DEV-11241] Declare support for document format v5

---

src/types/NewsroomTheme.ts

[DEV-11411] Declare `video_layout` as a theme feature flag

---

src/endpoints/Stories/Client.ts
src/endpoints/Stories/types.ts

Implementation: https://github.com/prezly/prezly/pull/14128
Declare `slug` property support to Story Create & Update APIs.

[DEV-12091] Feature - Story custom slugs

---

src/endpoints/Stories/types.ts
src/types/Story.ts

+ also rename `slug` to `custom_slug` in Story Create/Update API interfaces

[DEV-12202] Add `custom_slug` to Story API

---

src/types/Story.ts

See https://github.com/prezly/prezly/pull/14168/files#diff-8e5098fe3b709062818f287e1574e861f23900bb006adbd635b9485fd59ce977R92

[DEV-12132] Declare Story `auto_slug` property

---

package.json

Some of our themes are reporting security issues that are coming from this repository, so I've updated the affected packages.

Update dependencies that contained security issues

---

src/Client.ts
src/endpoints/ContactTags/Client.ts
src/endpoints/ContactTags/index.ts
src/endpoints/ContactTags/types.ts
src/endpoints/Contacts/Client.ts
src/endpoints/index.ts
src/routing.ts
src/types/ContactTag.ts
src/types/index.ts

Partially depends on https://github.com/prezly/prezly/pull/14697

[DEV-12883] Feature - Declare Contact Tags API + extend it

---

src/endpoints/ContactTags/Client.ts

Feature - Declare Contact Tags DeleteMany API endpoint

---

src/endpoints/Newsrooms/types.ts
src/types/Newsroom.ts

Requires https://github.com/prezly/prezly/pull/14746

[CARE-4942] Declare the new `onetrust_cookie_consent` API property

---

src/types/Story.ts

* https://github.com/prezly/prezly/pull/15092

Add coverages as referenced entities

---

src/types/common/OEmbedInfo.ts

Depends on https://github.com/prezly/prezly/pull/15169

[DEV-13306] Declare the new oEmbed API property

---

src/Client.ts
src/endpoints/CoverageIntegrations/Client.ts
src/endpoints/CoverageIntegrations/index.ts
src/endpoints/CoverageIntegrations/types.ts
src/endpoints/index.ts
src/routing.ts
src/types/CoverageEntry.ts
src/types/CoverageIntegration.ts
src/types/CoverageIntegrationRun.ts
src/types/index.ts

[CARE-6137] Add Coverage Integrations endpoint

---

src/endpoints/Coverage/types.ts

Didn't know those types are that duplicated 🙂

[DEV-13537] Fix - Update Coverage UpdateRequest interface

---

src/endpoints/Stories/Client.ts

[DEV-13860] Fix - Pass `auto: boolean` flag as payload to `/translate` API

---

src/api/DeferredJobsApiClient.ts

A regression introduced in #345

[DEV-18563] Fix API error catching&throwing @ DeferredJobsApiClient

---

src/types/CoverageEntry.ts
src/types/Story.ts

Related changes in the app:
- https://github.com/prezly/prezly/pull/15961
- https://github.com/prezly/prezly/pull/15959

[DEV-18879][DEV-18781] Document new coverage<>story matching properties

---

src/endpoints/Contacts/Client.ts
src/endpoints/Contacts/types.ts

See https://github.com/prezly/prezly/pull/16503

[DEV-19743] Declare `search` param support to Contacts API

---

src/types/SenderDomain.ts

Based on https://github.com/prezly/prezly/pull/17006

[DEV-20664] Feature - Add `microsoft_setup_recommended` field to SenderDomain

---

src/types/License.ts

Please review it together with https://github.com/prezly/prezly/pull/17293

[DEV-21104] Feature - Specify `demo_at` prop on License interface

---

src/endpoints/Campaigns/Client.ts
src/endpoints/Stories/Client.ts
src/types/BulkDeletePayload.ts
src/types/StoriesBulkSelector.ts
src/types/index.ts

Pitches are not part of SDK yet, but they should be supported at some point.

[DEV-21234] Feature - Stories & Campaigns bulk deletion
